export default {
    LEFT_MARGIN_TO_SHOW_OPTIONS : 220,
    DEFAULT_FOREGROUND_COLOR : '#000',
    DEFAULT_BACKGROUND_COLOR : '#fff',
    DEFAULT_FONT_SIZE : 14,
    DEFAULT_FONT_NAME : null,
    DEFAULT_SHOW_OPTIONS : false
}

